### ISSUE TITLE
Typo3 9 Routing

### ISSUE THREAD

**Issue by stemeda** [digedag/cfc_league_fe#68]
Hallo zusammen,

hat schon einer ein Beispiel für das Routing?

Danke und Gruß

**Comment by digedag** [comment]
Was genau meinst du mit Routing? Die sprechenden URIs?

**Comment by stemeda** [comment]
Ja genau. Ich hab mal angefangen mit dem hier:

```
routeEnhancers:                                                                                                                                                                                                                             
  CfcLeagueTable:                                                                                                                                                                                                                          
    type: Simple                                                                                                                                                                                                                           
    limitToPages: [1, 2, 3, 4, ...]                                                                                                                                                
    routePath: '/{cfc_league_fe__tabletype}'                                                                                                                                                                                               
    defaults:                                                                                                                                                                                                                              
      cfc_league_fe__tabletype: 0                                                                                                                                                                                                          
    requirements:                                                                                                                                                                                                                          
      cfc_league_fe__tabletype: '[0-2]{1}'
```

Evtl. hat ja schon jemand weitere Routings geschrieben und möchte das hier teilen :-)
